import type { Category } from 'types'

export const defaultCategories: Category[] = [
  {
    id: 'food',
    name: '餐饮',
    type: 'expense',
    icon: 'utensils',
    color: '#FF9800',
    enabled: true,
    isDefault: true,
    sort: 1,
  },
  {
    id: 'transport',
    name: '交通',
    type: 'expense',
    icon: 'bus',
    color: '#03A9F4',
    enabled: true,
    isDefault: true,
    sort: 2,
  },
  {
    id: 'shopping',
    name: '购物',
    type: 'expense',
    icon: 'shopping-bag',
    color: '#E91E63',
    enabled: true,
    isDefault: true,
    sort: 3,
  },
  {
    id: 'salary',
    name: '工资',
    type: 'income',
    icon: 'wallet',
    color: '#4CAF50',
    enabled: true,
    isDefault: true,
    sort: 1,
  },
  {
    id: 'parttime',
    name: '兼职',
    type: 'income',
    icon: 'briefcase',
    color: '#9C27B0',
    enabled: true,
    isDefault: true,
    sort: 2,
  },
]
